#!/usr/bin/php
<?php

use shortcut\App;

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

$app = new App();
$method = !empty($argv[1]) ? $argv[1] : 'main';


if (method_exists($app, $method) && is_callable([$app, 'main'])) { 
    $app->{$method}();
} else {
    echo 'Method does not exist or is not callable.';
    exit;
}