#!/usr/bin/php
<?php

use shortcut\App;

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

$app = new App();
$method = !empty($argv[1]) ? $argv[1] : 'main';
$param = !empty($argv[2]) ? $argv[2] : null;

if (method_exists($app, $method) && is_callable([$app, $method])) {
    $app->{$method}($param);
} else {
    echo 'Method does not exist or is not callable.';
    exit;
}